name: Package CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version:
          - "3.12"

    steps:
      - uses: actions/checkout@v3

      - name: Python ${{ matrix.python-version }} Setup
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/0.4.2/install.sh | sh

      - name: Install package
        run: uv sync --all-extras --dev

      - name: Run ruff
        shell: bash
        run: |
          uv run ruff check .
          uv run ruff format . --check

      - name: Run mypy
        shell: bash
        run: |
          uv run mypy src --config pyproject.toml

      - name: Run pytest
        shell: bash
        run: |
          uv run pytest tests --cov=src --cov-report=html --cov-report=xml --cov-branch

      - name: Upload coverage HTML
        uses: actions/upload-artifact@v4
        with:
          name: unit-coverage-html
          path: htmlcov

      - name: Upload coverage XML
        uses: actions/upload-artifact@v4
        with:
          name: unit-coverage-xml
          path: coverage.xml

      - name: Run covcheck
        shell: bash
        run: |
          uv run covcheck coverage.xml --config pyproject.toml
